"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = __importDefault(require("../../modules/auth/auth.routes"));
const reviews_routes_1 = __importDefault(require("../../modules/reviews/reviews.routes"));
const book_route_1 = __importDefault(require("../../modules/books/book.route"));
const users_routes_1 = __importDefault(require("../../modules/users/users.routes"));
const progress_routes_1 = __importDefault(require("../../modules/progress/progress.routes"));
const wishlist_routes_1 = __importDefault(require("../../modules/wishlist/wishlist.routes"));
const router = (0, express_1.Router)();
router.use('/auth', auth_routes_1.default);
router.use('/reviews', reviews_routes_1.default);
router.use('/books', book_route_1.default);
router.use('/users', users_routes_1.default);
router.use('/progress', progress_routes_1.default);
router.use('/wishlist', wishlist_routes_1.default);
exports.default = router;
